### ISSUE TITLE
copytoclipboard.js

### ISSUE THREAD

**Issue by WEKINBAD** [pnthach95/spicetify-extensions#1]
Not working for me and it was removed from marketplace, could you explain how to install it manually

**Comment by pnthach95** [comment]
You have to use `copytoclipboard2.js` file and use [this doc](https://spicetify.app/docs/advanced-usage/extensions) to know how to install manually

**Comment by Tetrax-10** [comment]
why is it not available in the marketplace? publish it in marketplace

**Comment by pnthach95** [comment]
> why is it not available in the marketplace? publish it in marketplace

It's available in marketplace. If you don't see it, try to update marketplace app.

![image](https://user-images.githubusercontent.com/31266357/180365108-75ebbb68-8f61-46f1-ba6c-921fab6c84e6.png)
