### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by rosgr100** [pnthach95/spicetify-extensions#11]
I got it fixed.

sorry

**Comment by rosgr100** [comment]
Extension doesn't work anymore, tried to manual install it or use the one from the marketplace but none seems to work.

Thank you

**Comment by pnthach95** [comment]
It works on my app, install from marketplace

Spotify for Windows (64 bit)
1.2.16.947.gcfbaa410
Spicetify v2.22.0
Theme: Comfy / Comfy
Extensions: romaji_lyrics.js, copytoclipboard2.js, comfy.js
Custom apps: marketplace, new-releases

**Comment by rosgr100** [comment]
Spotify for Windows (64 bit)
1.2.16.947.gcfbaa410
Spicetify v2.22.0
Theme: marketplace
Extensions: djinfo.js, copytoclipboard2.js, playlistFilter.js, spotifyGenres.js, spotifyBackup.js, star-ratings.js, sortByPlayCount.js
Custom apps: marketplace


![Screenshot 2023-07-25 152619](https://github.com/pnthach95/spicetify-extensions/assets/74199552/4cfb089e-0d56-4f0c-b30c-853d71fd51ea)

**Comment by pnthach95** [comment]
Follow instruction to provide me debug log:
- Enable DevTools if you didn't:
	- Open cmd and run `spicetify enable-devtools`
	- Wait for Spotify restart
- Right-click at blank space and click `Show DevTools`
- Open `Console` tab in DevTools window
- Switch to Spotify window, try to do some copy actions
- Back to Console, right-click and click `Save as`
- Comment with log file you saved

**Comment by rosgr100** [comment]
[xpui.app.spotify.com-1690289539841.log](https://github.com/pnthach95/spicetify-extensions/files/12161436/xpui.app.spotify.com-1690289539841.log)


![Screenshot 2023-07-25 160758](https://github.com/pnthach95/spicetify-extensions/assets/74199552/f0a4fb9a-f2af-4e0f-be11-18f364985a51)

**Comment by rosgr100** [comment]
Thank you!
