### ISSUE TITLE
Copy Text - No Longer An Option

### ISSUE THREAD

**Issue by ZotacAviation** [pnthach95/spicetify-extensions#16]
Hello! I've suddenly lost this option for both of my computers.

Spotify for Windows (64 bit)
1.2.19.941.gbf202593
Spicetify v2.23.1

I followed some of the debug instructions [found here](https://github.com/pnthach95/spicetify-extensions/issues/11#issuecomment-1649774918):

[xpui.app.spotify.com-1694226466225.log](https://github.com/pnthach95/spicetify-extensions/files/12564425/xpui.app.spotify.com-1694226466225.log)

![image](https://github.com/pnthach95/spicetify-extensions/assets/40968899/786aa5c7-9cf3-4d69-b805-929111775d76)

**Comment by pnthach95** [comment]
That is not my code. What file did you took screenshot?

**Comment by ZotacAviation** [comment]
> That is not my code. What file did you take screenshot?

My bad, I didn't know what I was doing. I updated the photo with the only error I could find.

![image](https://github.com/pnthach95/spicetify-extensions/assets/40968899/786aa5c7-9cf3-4d69-b805-929111775d76)

**Comment by pnthach95** [comment]
I changed the path of file. Reinstall it to fix

**Comment by ZotacAviation** [comment]
> I changed the path of file. Reinstall it to fix

Ah, it works now. Thank you so much!
