### ISSUE TITLE
Request to API fails with error

### ISSUE THREAD

**Issue by Andryshik345** [pnthach95/spicetify-extensions#17]
Hello, an extension stopped working again.

Client version is 1.2.31.1205
Spicetify is 2.31.3

[xpui.app.spotify.com-1708143595807.log](https://github.com/pnthach95/spicetify-extensions/files/14317726/xpui.app.spotify.com-1708143595807.log)

![изображение](https://github.com/pnthach95/spicetify-extensions/assets/24612088/1d3bd962-9a0b-4d76-bc9e-48ee30272b49)

**Comment by pnthach95** [comment]
I just tested. It works on my laptop. Try reinstall extension

**Comment by Andryshik345** [comment]
@pnthach95 Already tried several times. Alright, apparently the problem is on my side then (although the songs load fine). I'll close the issue for now.

**Comment by pnthach95** [comment]
@Andryshik345 send me the song, let me try

**Comment by Andryshik345** [comment]
@pnthach95 It wasn't really tied to some song, it is more likely of different region i'm using in spotify (so invalidated token or some sort of thing).
But you can try on Waifu Shop - Roll the Dice, if you want.

**Comment by pnthach95** [comment]
Look like my spicetify got cached or something, it stops working today

**Comment by pnthach95** [comment]
I fixed it. If auto-update doesn't work, try to reinstall
