### ISSUE TITLE
Attempting to copy anything now results in Cannot destructure property 'operation' of 't' as it is undefined.

### ISSUE THREAD

**Issue by f1at1ander** [pnthach95/spicetify-extensions#18]
From About Spotify:

Spotify for macOS (Apple Silicon)
1.2.32.997.g4c6498b6
Spicetify v2.33.0
xpui_2024-02-23_1708709925614_4c6498b
cef_121.3.15+g4d3b0b4+chromium-121.0.6167.184
Runtime: Alloy

Recently I had to update to Spicetify 2.33.0 after Spicetify stopped working due to a Spotify client update (I'm on versino . After doing so, I found that I'm getting a new error when trying to copy an artist name, song tile, or album title. Specifically, a pop-up appears which says "Error: Cannot destructure property 'operation' of 't' as it is undefined."

Here's the full error from the the Console tab of DevTools. I also checked the Network tab but it doesn't look like the API request is even sent.

I even tried the "Extended copy" extension that another dev has made, and the exact same error occurs in the Console tab; at the risk of stating the obvious, this seems to strongly imply you're both affected in the same way by a change to the Spotify client's behavior.

Sorry for the trouble so soon after you fixed the last issue (which someone else reported), and thanks in advance for your help!

```
TypeError: Cannot destructure property 'operation' of 't' as it is undefined.
    at Object.<anonymous> (xpui.js:1:938148)
    at copytoclipboard.js?time=1709170660197:1:1436
    at Spicetify.ContextMenu.Item.t (copytoclipboard.js?time=1709170660197:1:1617)
    at onClick (spicetifyWrapper.js:1699:6)
    at onClick (spicetifyWrapper.js:1467:7)
    at xpui.js:1:108717
    at Object.Me (vendor~xpui.js:1:2260885)
    at He (vendor~xpui.js:1:2261039)
    at vendor~xpui.js:1:2280921
    at Ui (vendor~xpui.js:1:2281015)
    at Vi (vendor~xpui.js:1:2281429)
    at vendor~xpui.js:1:2286867
    at ul (vendor~xpui.js:1:2350238)
    at Pe (vendor~xpui.js:1:2260018)
    at Ki (vendor~xpui.js:1:2282721)
    at jt (vendor~xpui.js:1:2267132)
    at Yt (vendor~xpui.js:1:2266916)
    at HTMLDivElement.i (vendor~xpui.js:1:176123)
```

**Comment by pnthach95** [comment]
I don't get update, still at 1.2.31.1205.g4d59ad7c. I check it later

**Comment by pnthach95** [comment]
Hey, can you try again with Spicetify v2.33.2? I updated and copy function works again

**Comment by f1at1ander** [comment]
Confirmed! Sorry, next time I'll wait for another Spicetify update before raising an issue.

**Comment by SydneyNS** [comment]
It's happening again after the most recent Spotify update.

**Comment by pnthach95** [comment]
You can't copy artist name. That's the bug
