### ISSUE TITLE
copy 2 things 

### ISSUE THREAD

**Issue by pravendrakushwaha** [pnthach95/spicetify-extensions#4]
how can i copy artist and name at the same time ?
im using cli mode !

**Comment by pnthach95** [comment]
You mean song name and artist name? I think it can be done

**Comment by pravendrakushwaha** [comment]
not working only name is working not artist name !

**Comment by pravendrakushwaha** [comment]
i installed it from CLI not marketplace

**Comment by pravendrakushwaha** [comment]
function sendToClipboard(text) {
        if (text) {
            Spicetify.showNotification(`copied : ${text}`);
            Spicetify.Platform.ClipboardAPI.copy(text);
        }
    }

    function shouldAddContextMenu(uris) {
        if (uris.length === 1) {
            const uri = Spicetify.URI.fromString(uris[0]);
            switch (uri.type) {
                case Type.TRACK:
                case Type.ALBUM:
                case Type.ARTIST:
                case Type.PLAYLIST:
                case Type.PLAYLIST_V2:
                case Type.SHOW:
                    return true;
                default:
                    return false;
            }
        } else {
            return false;
        }
    }

    new Spicetify.ContextMenu.Item("Copy Text", getText, shouldAddContextMenu, "copy").register();
}

**Comment by pravendrakushwaha** [comment]
function sendToClipboard(text) {
        if (text) {
            Spicetify.showNotification(`copied : ${text}`);
            Spicetify.Platform.ClipboardAPI.copy(text);
        }
    }

    function shouldAddContextMenu(uris) {
        if (uris.length === 1) {
            const uri = Spicetify.URI.fromString(uris[0]);
            switch (uri.type) {
                case Type.TRACK:
                case Type.ALBUM:
                case Type.ARTIST:
                case Type.PLAYLIST:
                case Type.PLAYLIST_V2:
                case Type.SHOW:
                    return true;
                default:
                    return false;
            }
        } else {
            return false;
        }
    }

    new Spicetify.ContextMenu.Item("Copy Text", getText, shouldAddContextMenu, "copy").register();
}

**Comment by pravendrakushwaha** [comment]
``` function sendToClipboard(text) {
        if (text) {
            Spicetify.showNotification(`copied : ${text}`);
            Spicetify.Platform.ClipboardAPI.copy(text);
        }
    }

    function shouldAddContextMenu(uris) {
        if (uris.length === 1) {
            const uri = Spicetify.URI.fromString(uris[0]);
            switch (uri.type) {
                case Type.TRACK:
                case Type.ALBUM:
                case Type.ARTIST:
                case Type.PLAYLIST:
                case Type.PLAYLIST_V2:
                case Type.SHOW:
                    return true;
                default:
                    return false;
            }
        } else {
            return false;
        }
    }

    new Spicetify.ContextMenu.Item("Copy Text", getText, shouldAddContextMenu, "copy").register();
}

**Comment by pravendrakushwaha** [comment]
```
function sendToClipboard(text) {
        if (text) {
            Spicetify.showNotification(`copied : ${text}`);
            Spicetify.Platform.ClipboardAPI.copy(text);
        }
    }

    function shouldAddContextMenu(uris) {
        if (uris.length === 1) {
            const uri = Spicetify.URI.fromString(uris[0]);
            switch (uri.type) {
                case Type.TRACK:
                case Type.ALBUM:
                case Type.ARTIST:
                case Type.PLAYLIST:
                case Type.PLAYLIST_V2:
                case Type.SHOW:
                    return true;
                default:
                    return false;
            }
        } else {
            return false;
        }
    }

    new Spicetify.ContextMenu.Item("Copy Text", getText, shouldAddContextMenu, "copy").register();
}

**Comment by pnthach95** [comment]
I haven't worked on this feature yet

**Comment by pnthach95** [comment]
Just push a commit. Can you check and close issue?

https://user-images.githubusercontent.com/31266357/205239053-cd0c86ae-f1b6-4407-9b4e-4f99e6636817.mov

**Comment by pravendrakushwaha** [comment]
![Screenshot (1037)](https://user-images.githubusercontent.com/17412877/205241542-3e219454-530a-4266-bf36-eccc83c64162.png)



THERE IS NO BUTTON !!!

**Comment by pnthach95** [comment]
Do you run `spicetify apply` after paste new file to `Extensions` folder?

**Comment by pravendrakushwaha** [comment]
yaaa im using urs copytoclipboard2 file

**Comment by pravendrakushwaha** [comment]
should i close the issue ? 
its okay !!

**Comment by pravendrakushwaha** [comment]
bro its working now !!!
![Screenshot (1038)](https://user-images.githubusercontent.com/17412877/205244064-2f32ec1d-9146-4fc7-b940-b313b7e58702.png)
